### ISSUE TITLE
Bug: Missing offset in response in 0.10.1

### ISSUE THREAD

**Issue by JurajNyiri** [IBM/cloudant-node-sdk#1609]
**Describe the bug**
Offset is missing from the response.

**To Reproduce**
1. Execute `.postView` with following example arguments:

```
{
  db: 'CHANGE_ME',
  ddoc: 'CHANGE_ME',
  view: 'CHANGE_ME',
  keys: undefined,
  limit: 1,
  includeDocs: false,
  skip: undefined,
  startKeyDocId: undefined,
  startKey: '2024-08-21T08:35:15.899Z', // change me to some startKey based on the view
  endKey: undefined
}
```

2. Observe offset is not returned in the latest version

**Expected behavior**
Offset to be returned.
This is response from cloudant REST endpoint:
<img width="224" alt="68747470733a2f2f7a656e6875622e69626d2e636f6d2f696d616765732f3561656231623339363539393532653535613833383731612f37303537653664612d363565372d343635362d613431312d633233303731626334396661" src="https://github.com/user-attachments/assets/08338950-b7d4-4b85-8f81-55beb3462064">

After conversion inside https://github.com/IBM/node-sdk-core/blob/main/lib/base-service.ts#L313, it is dropped.

<img width="215" alt="68747470733a2f2f7a656e6875622e69626d2e636f6d2f696d616765732f3561656231623339363539393532653535613833383731612f33643730313035382d363239642d343731632d613937342d353963386636386632343135" src="https://github.com/user-attachments/assets/275f6ecf-157c-4dc6-8097-244e9808146e">

This is caused by `deserializerFn` https://github.com/IBM/cloudant-node-sdk/blob/main/cloudant/v1.ts#L11066 not having "offset" parameter. After adding it there, like so, it is properly returned.

```
if (obj.offset !== undefined) {
        copy.offset = obj.offset;
}
```

**Must gather (please complete the following information):**
 - SDK Version: 5.0.1 / 0.10.1
 - Node.js Version: 18
 - Name of service that you're trying to use (if applicable)
 - Name of operation that you're trying to invoke (if applicable)

**Additional context**
This is causing issues for our services with offset based logic, calculating when to stop processing the data and showing a proper progress.

It happened sometimes after update from 0.8.x to 0.10.1, most probably inside 0.9.0 introducing other breaking changes, including the map of `total_rows` to `totalRows`.

I was not able to properly compile the ts code and test a fix due to tsc errors I do not have time to investigate how to fix, but an example idea of a fix can be seen inside https://github.com/JurajNyiri/node-sdk-core/commit/3f8de97fa81ae3025568e736eaf66fc585f0a349 .

Alternatively, a condition could be added to also process integers similar to strings (but then other integers being renamed, like totalRows need to be dropped).

**Comment by ricellis** [comment]
The `offset` property has always been intentionally excluded from the SDK's declared API model of a view response as per the documentation for `postView` [here](https://cloud.ibm.com/apidocs/cloudant?code=node#postview) and [here](https://ibm.github.io/cloudant-node-sdk/docs/0.10.1/classes/CloudantV1.ViewResult-1.html).

Prior to version `0.9.0` the SDK model was not enforced and a raw response was returned, which is why the `offset` property was visible to `js` code access (but actually would not have compiled in TS).

If you require it, It is possible to obtain a raw response by using [`postViewAsStream`](https://ibm.github.io/cloudant-node-sdk/docs/0.10.1/classes/CloudantV1-1.html#postViewAsStream).

>This is causing issues for our services with offset based logic, calculating when to stop processing the data and showing a proper progress.

The `offset` and `total_rows` are related to the complete indexed view and disregard the effects of narrowing parameters passed in the request. For this reason they are not reliable for determining progress though a view. Further the `offset` should certainly not be used for any pagination of views as the position in the view can change between requests. Suitable means of pagination through views are described in the [documentation](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-pagination-and-bookmarks#pagination-of-views).

**Comment by JurajNyiri** [comment]
Thank you, that was very helpful, [postViewAsStream](https://ibm.github.io/cloudant-node-sdk/docs/0.10.1/classes/CloudantV1-1.html#postViewAsStream) works as expected and returns offset.

As for the pagination concerns, we do paginate using startKey, not offset. We however use it (along with total rows) to show us how many assets are left to process in a view and to show progress of the processing.
