### ISSUE TITLE
Investigate "Dependency warnings" in CI builds

### ISSUE THREAD

**Issue by emlaver** [IBM/cloudant-node-sdk#39]
https://travis-ci.com/github/IBM/cloudant-node-sdk/jobs/434834758#L416-L419

**Comment by ricellis** [comment]
AFAICT this is because neither the package `@types/node` nor `extend` declare an `engines` block in their `package.json` - this results in a [warning](https://github.com/voxpelli/node-installed-check-core/blob/4242ed5cffabbcfb3ab50ba6df786bf06e4a6197/lib/check-engine-versions.js#L57).

We are effectively asking for those warnings in our package.json `check-packages` script by using:
`    "check-packages": "installed-check -e -d -v"`
if instead we turned of verbose by using:
`    "check-packages": "installed-check -e -d"`
then we would not see those warnings.

It seems that this output is confusing, so probably suppressing it is the right thing to do.

**Comment by ricellis** [comment]
This was resolved by https://github.com/IBM/cloudant-node-sdk/pull/280
