### ISSUE TITLE
How to perform functions query in design document

### ISSUE THREAD

**Issue by saristar** [IBM/cloudant-node-sdk#390]
Hi,

For my project I have a requirement to perform functions in design document as given below.
list functions - https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-design-documents#list-functions, 
show functions - https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-design-documents#show-functions
update handles - https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-design-documents#update-handlers

Could you please help if this is enabled in sdk?

**Comment by mojito317** [comment]
Hi @saristar!

The functions are not enabled in the sdk _yet_. The update handler is in our TODO queue, but unfortunately, no estimated delivery time at the moment. We have not put the show and list functions in our TODO queue yet, we have to reconsider them.

However, it's worth mentioning these functions will be deprecated [in CouchDB 4.0](https://docs.couchdb.org/en/stable/whatsnew/3.0.html#deprecated-feature-warnings), I do not know whether Cloudant will follow them, or keep these functions in the future as well.

**Comment by saristar** [comment]
Hi @mojito317,

As there is no deprecation details about these functions in cloudant db, may I know like by when can I have it in the sdk?
I'm using this sdk only as a replacement for nodejs-cloudant npm package.

I see that few things are mentioned [here](https://github.com/cloudant/nodejs-cloudant/blob/master/MIGRATION.md) about the migration but would it possible to add also the TODO items in this list?

**Comment by mojito317** [comment]
> As there is no deprecation details about these functions in cloudant db, may I know like by when can I have it in the sdk?
> I'm using this sdk only as a replacement for nodejs-cloudant npm package.

There is no decision and no estimated delivery time at the moment. We will return to you if I know more.

> I see that few things are mentioned [here](https://github.com/cloudant/nodejs-cloudant/blob/master/MIGRATION.md) about the migration but would it possible to add also the TODO items in this list?

Good idea! We will take this into consideration!

**Comment by ricellis** [comment]
Whilst these functions remain usable (for now [when using legacy creds](https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-managing-access-for-cloudant#unavailable-endpoints-ai)) in the Cloudant service as noted above they are [deprecated since CouchDB 3.0](https://docs.couchdb.org/en/stable/whatsnew/3.0.html#deprecated-feature-warnings). The fact they are still present (or not marked deprecated) in the Cloudant docs is an oversight which I have asked to be corrected. These operations are not present in [Cloudant's API reference docs](https://cloud.ibm.com/apidocs/cloudant).

You are, of course, able to continue using them while they are available in the service if you see fit, but we won't be adding these functions to the SDK as we do not want to encourage new usages of obsolete API. Code rewrites during SDK migration are a good opportunity to replace usage of the obsolete APIs with client side alternatives.
