### ISSUE TITLE
Create document asks _id as required field.

### ISSUE THREAD

**Issue by saristar** [IBM/cloudant-node-sdk#398]
When I'm creating a document, using `postDocument` method it asks for two fields as required fields. i.e. db and document. And in the db it searches for _id and throws `illegal_docid` error if not present.

In the previous `nodejs-cloudant` library _id was not a mandatory field. With just db_name we could create a document.

**To Reproduce**
Create document with just db name.
```
const productsDoc = CloudantV1.Document = {
    name: 'Document 1'
};  
service.postDocument({
  db: 'products',
  document: productsDoc
}).then(response => {
  console.log(response.result);
}).catch(error => {
    console.log('=========> error: ', error);
})
```

**Expected behavior**
It should create document with just db name as mandatory field.

**Screenshots**
Error for not passing _id
![mandatory_issue](https://user-images.githubusercontent.com/87409095/127325568-ed6035e4-55cf-4e45-87ff-05eb0fdd5694.PNG)

**Comment by mojito317** [comment]
Hi!

It looks to me you are trying to add a document to a partitioned database where it is necessary to add an `_id` like this: `partition:id` with the `:` separator between the partition id and the decument id.

If you try to add a document to a non-partitioned database, it will succeed even without an `_id` field.

**Comment by ricellis** [comment]
Closing; as @mojito317 says if you use a _non-partitioned_ DB then you can create a document with just a DB name and your document content (without any `_id` field).
`_id` is (and has always been) required for documents in _partitioned_ DBs because the partition key is part of the `_id` and the database doesn't know which partition to store the document in without it.
