### ISSUE TITLE
Query related to attachment related filters

### ISSUE THREAD

**Issue by kvv002** [IBM/cloudant-node-sdk#461]
Hi,
As per the [documentation](https://cloud.ibm.com/apidocs/cloudant?code=node#getdocument), I am trying to get the **att_encoding_info** for the compressed attachments which I assume is .zip, .7z files.
The response doesnt seem to change when I make the filter as **true**, **false**.
Below is my sample response with and without enabling the encoding info
```
{
  "_id": "xyz",
  "_rev": "4-6",
  "type": "product",
  "productid": "1000042",
  "brand": "Salter",
  "name": "Digital Kitchen Scales",
  "description": "Slim Colourful Design Electronic Cooking Appliance for Home / Kitchen, Weigh up to 5kg + Aquatronic for Liquids ml + fl. oz. 15Yr Guarantee - Green",
  "price": 14.99,
  "image": "assets/img/0gmsnghhew.jpg",
  "_revisions": {
    "start": 4,
    "ids": [
      "6",
      "7",
      "f",
      "a"
    ]
  },
  "_attachments": {
    "BinaryImage_2_2.zip": {
      "content_type": "application/x-zip-compressed",
      "revpos": 4,
      "digest": "md5-PoNvi8uCx7zdW9tqIllvEQ==",
      "length": 784878,
      "stub": true
    },
    "BinaryImage": {
      "content_type": "application/octet-stream",
      "revpos": 3,
      "digest": "md5-1Qmf7GHXzhBcNUfRJgTIgQ==",
      "length": 784340,
      "stub": true
    },
    "BinaryImage.7z": {
      "content_type": "application/octet-stream",
      "revpos": 2,
      "digest": "md5-wuq3cCZTvKu11nA1poEEgg==",
      "length": 784522,
      "stub": true
    }
  }
}
```

Also I am trying to use **att_since** filter with the sample revision Ids, but that sends the whole response from 1st revision onwards, below is my query:

```
service.getDocument({
    db: 'xyz',
    attEncodingInfo: true,
    docId: 'small-appliances:1000042',
    att_since: ["3-7.."],
    revs: true
  }).then(response => {
    console.log('getDocument:---', JSON.stringify(response.result));
  });
```
Any inputs will be of great help,
Thank you

**Comment by mojito317** [comment]
Hi @kvv002!

The compressible types on Cloudant are: `text/*`, `application/javascript`, `application/json`, and `application/xml` (see the [CouchDB doc](https://docs.couchdb.org/en/main/config/misc.html#attachments/compressible_types)). 

This means that if you save e.g. a `text/plain` attachment it'll get gzipped and `content-encoding` added, but for a `image/jpeg` it will not. In general, images are served unencoded because the image compression technology itself has already compressed the data, and e.g. zipping it might even make it larger.

If you would like to save images as attachments, use the correct `content-type` (i.e `image/jpeg` in case of a JPEG image).

**Comment by kvv002** [comment]
Thanks @mojito317 , another query I had related **conflicts**, I wanted to try some of the conflict related filters, but for that I need to first create a conflicting document, I tried some 5 **parallel** calls to achieve the same, but it doesnt seem to help.
Could you please provide some input of how can I create a conflict document

Thank you

**Comment by mojito317** [comment]
Hi @kvv002! I think this is rather a Cloudant support or CouchDB slack question (as this isn't specifically related to this SDK), but if you follow [this Stackoveflow thread](https://stackoverflow.com/questions/7602615/how-can-you-simulate-a-conflict-in-couchdb-without-using-replication/7604701), you will get your answer. Note the thread is a bit out-of-date, the API has changed since then. It is also worth learning a bit about the revision tree from the [Cloudant blog](https://blog.cloudant.com/2017/01/01/The-Cloudant-Revision-Tree.html).

**Comment by kvv002** [comment]
Thanks @mojito317 for all the help
