### ISSUE TITLE
Add Node 18, remove 12 support

### ISSUE THREAD

**Issue by emlaver** [IBM/cloudant-node-sdk#799]
Node 12 is a bit over 2 weeks away from EOL: https://endoflife.date/nodejs.  Node 18 will be release on April 19th: https://nodejs.org/en/about/releases/.  
Update the engine statement and Travis to 14, 16, and 18.

**Comment by ricellis** [comment]
Agree we should remove 12 from test matrix and supported engines.
Agree we should add 18 to the test matrix, but I don't think we should add it to the engine statement.

As per [Node.js releases](https://nodejs.org/en/about/releases/#releases)
>Production applications should only use Active LTS or Maintenance LTS releases.

Node 18 won't become Active LTS until October - so that's when it should move into our "supported" list.

**Comment by ricellis** [comment]
We should also update the Node types dependency to 14.x from 12.x with this change.
https://github.com/IBM/cloudant-node-sdk/blob/1f3da9f1f28b7a0e7f45e339c76b60abc19a3bef/package.json#L38
